In [1]:
import numpy as np

A = np.array ([[1,2], [3,4]])
print("2x2 matrix :\n", A)

B = np.array ([[6,1,4], [3, 4, 5], [2, 9, 5]])
print("3x3 matrix :\n", B)

2x2 matrix :
 [[1 2]
 [3 4]]
3x3 matrix :
 [[6 1 4]
 [3 4 5]
 [2 9 5]]


In [2]:
import numpy as np
x = np.array ([[2,5], [ 3, 8]])
y = np.array ([[1, 4], [6, 9]])

#dotproduct of two matrices
z = np.dot(x, y)
print("xy :\n", z)

xy :
 [[32 53]
 [51 84]]


In [3]:
import numpy as np
c = np.array([[1, 3, 5, 7], [2, 4, 6, 8]])

#Transpose of the matrix
d= np.transpose(c)

print("Transpose of c :/n", d)

Transpose of c :/n [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [4]:
import numpy as np
a = np.array([[2, 5, 7], [3, 6, 9], [1, 8, 4]])

#Inverse of the matrix
v = np.linalg.inv(a)
print("Inverse of matrix a : \n", v)

Inverse of matrix a : 
 [[-3.2         2.4         0.2       ]
 [-0.2         0.06666667  0.2       ]
 [ 1.2        -0.73333333 -0.2       ]]


In [5]:
import numpy as np
b = np.array([[11, 23, 45], [13, 24, 35], [24, 35, 25]])

#Determinant of the matrix
d = np.linalg.det(b)
print("Determinant of b :\n", d)

Determinant of b :
 -474.9999999999992


In [6]:
import numpy as np
from numpy.linalg import eig

a = np.array([[1, 3, 5], [2, 4, 6], [7, 0, 9]])


#Eigen value and vector of the matrix
c,d = eig(a)
print("E-value:", c)
print("E-vector:", d)




E-value: [13.21110255 -1.21110255  2.        ]
E-vector: [[ 0.42823805  0.78220784 -0.40824829]
 [ 0.55667235  0.31719546 -0.81649658]
 [ 0.71184834 -0.53622563  0.40824829]]
